export const toDoLists = [
  {
    id: 1,
    title: "Viagem para Aracati",
    toDoType: 1,
    tags: ["férias", "passear", "fim-de-semana"],
    toDos: [
      { id: 12321234, toDo: "Passear na praia" },
      { id: 22341188, toDo: "Ver por do sol" },
      { id: 62895014, toDo: "Andar de jangada" },
    ],
  },
  {
    id: 2,
    title: "Compras da semana",
    toDoType: 4,
    tags: ["gastos", "super mercado"],
    toDos: [
      { id: 45271235, toDo: "5KG Arroz" },
      { id: 78411890, toDo: "3KG Feijão" },
    ],
  },
  {
    id: 3,
    title: "Estudar para a prova",
    toDoType: 1,
    tags: ["escola", "estudo", "exame"],
    toDos: [
      { id: 56781234, toDo: "Revisar matéria" },
      { id: 91091188, toDo: "Resolver exercícios" },
      { id: 12131415, toDo: "Fazer resumo" },
    ],
  },
  {
    id: 4,
    title: "Limpar o apartamento",
    toDoType: 1,
    tags: ["casa", "tarefas domésticas"],
    toDos: [
      { id: 16171819, toDo: "Lavar louça" },
      { id: 20212223, toDo: "Passar aspirador de pó" },
      { id: 24252627, toDo: "Organizar a despensa" },
    ],
  },
  {
    id: 5,
    title: "Planejar festa de aniversário",
    toDoType: 1,
    tags: ["celebração", "organização", "eventos"],
    toDos: [
      { id: 28293031, toDo: "Escolher tema" },
      { id: 32333435, toDo: "Fazer lista de convidados" },
      { id: 36373839, toDo: "Comprar decoração" },
    ],
  },
  {
    id: 6,
    title: "Fazer exercícios físicos",
    toDoType: 2,
    tags: ["saúde", "atividade física"],
    toDos: [
      { id: 40414243, toDo: "Correr 5km" },
      { id: 44454647, toDo: "Fazer abdominais" },
      { id: 48495051, toDo: "Alongar" },
    ],
  },
  {
    id: 7,
    title: "Aprender a cozinhar",
    toDoType: 2,
    tags: ["culinária", "receitas"],
    toDos: [
      { id: 52535455, toDo: "Fazer um bolo" },
      { id: 56575859, toDo: "Preparar um jantar completo" },
      { id: 60616263, toDo: "Experimentar uma nova receita" },
    ],
  },
  {
    id: 8,
    title: "Organizar documentos",
    toDoType: 3,
    tags: ["papelada", "arquivos"],
    toDos: [
      { id: 64656667, toDo: "Separar contas pagas" },
      { id: 68697071, toDo: "Arquivar documentos importantes" },
      { id: 72737475, toDo: "Digitalizar papéis" },
    ],
  },
  {
    id: 9,
    title: "Fazer compras online",
    toDoType: 3,
    tags: ["compras", "internet"],
    toDos: [
      { id: 76777879, toDo: "Pesquisar produtos" },
      { id: 80818283, toDo: "Comparar preços" },
      { id: 84858687, toDo: "Fazer o pagamento" },
    ],
  },
  {
    id: 10,
    title: "Assistir a uma série",
    toDoType: 2,
    tags: ["entretenimento", "TV"],
    toDos: [
      { id: 88899091, toDo: "Escolher uma série para assistir" },
      { id: 92939495, toDo: "Preparar snacks" },
      { id: 96979899, toDo: "Maratonar os episódios" },
    ],
  },
  {
    id: 11,
    title: "Cuidar das plantas",
    toDoType: 3,
    tags: ["jardinagem", "natureza"],
    toDos: [
      { id: 100101102, toDo: "Regar as plantas" },
      { id: 103104105, toDo: "Podar as folhas secas" },
      { id: 106107108, toDo: "Adubar o solo" },
    ],
  },
  {
    id: 12,
    title: "Ler um livro",
    toDoType: 3,
    tags: ["leitura", "literatura"],
    toDos: [
      { id: 109110111, toDo: "Escolher um livro para ler" },
      { id: 112113114, toDo: "Encontrar um local tranquilo" },
      { id: 115116117, toDo: "Iniciar a leitura" },
    ],
  },
  {
    id: 13,
    title: "Fazer um projeto DIY",
    toDoType: 3,
    tags: ["criatividade", "artesanato"],
    toDos: [
      { id: 118119120, toDo: "Escolher um projeto" },
      { id: 121122123, toDo: "Comprar os materiais necessários" },
      { id: 124125126, toDo: "Colocar a mão na massa" },
    ],
  },
  {
    id: 14,
    title: "Aprender a tocar um instrumento",
    toDoType: 3,
    tags: ["música", "hobbies"],
    toDos: [
      { id: 127128129, toDo: "Escolher um instrumento" },
      { id: 130131132, toDo: "Encontrar aulas ou tutoriais online" },
      { id: 133134135, toDo: "Praticar regularmente" },
    ],
  },
  {
    id: 15,
    title: "Fazer um curso online",
    toDoType: 3,
    tags: ["aprendizado", "educação"],
    toDos: [
      { id: 136137138, toDo: "Pesquisar cursos de interesse" },
      { id: 139140141, toDo: "Escolher um curso" },
      { id: 142143144, toDo: "Dedicar tempo aos estudos" },
    ],
  },
];